### ISSUE TITLE
The ideas coincide

### ISSUE THREAD

**Issue by daxiondi** [avstack/jibri-pod-controller#1]
I have been researching jitsi-meet. 
Since a jibri can only record one meeting, this cannot satisfy my users. 
I recommend using the local-recording solution to solve it. 
Unfortunately, in some cases, the recording file will be lost, 
so I Thinking of using k8s' dynamic scaling to solve this problem,
I saw this warehouse today, which was consistent with my idea, which really made me very excited.
Does the recording on avstack use this solution? 
Will he lose the recording file? Is this a good solution?

**Comment by jbg** [comment]
We use this solution on AVStack, and we've found it to be robust. We've never lost a recording.

**Comment by daxiondi** [comment]
This is really a happy thing, the work you do is so exciting.
