### ISSUE TITLE
Add log rotate config ?

### ISSUE THREAD

**Issue by Tinkesh-Kumar** [avstack/jibri-pod-controller#3]

**Comment by jbg** [comment]
Could you explain what you mean? `jibri-pod-controller` just logs to stdout, not to files, so what would be rotated? It would normally be deployed as a container in a Kubernetes cluster, so saving the stdout output into log files, and managing those files, is handled by the kubelet.

**Comment by Tinkesh-Kumar** [comment]
Thanks for clarification. I am closing the issue.
