### ISSUE TITLE
Get an issue with starting jibri controller pod

### ISSUE THREAD

**Issue by lephat08** [avstack/jibri-pod-controller#6]
I think I have got issues with Dockerfile because the jibri pod show that the container could not be restarted (back-off)
However, running the docker build with the Dockerfile had no error.
Could you help me to solve this problem?
![image](https://user-images.githubusercontent.com/45971257/223021984-403ab532-f3bb-4e1b-9cba-e7463a73d06a.png)
![image](https://user-images.githubusercontent.com/45971257/223022052-9da04cb4-a157-4766-82e9-294561985a9c.png)

**Comment by jbg** [comment]
Look at the logs of the container to see why it is crashing on startup.

**Comment by lephat08** [comment]
> Look at the logs of the container to see why it is crashing on startup.

actually I could not exec to the container or get log from pod :(

**Comment by jbg** [comment]
You can't exec to a container that is not running. You can get the logs using kubectl though.

**Comment by jbg** [comment]
From your screenshot, there do not appear to be any environment variables configured for the `jibri-pod-controller` container. `jibri-pod-controller` will be logging an error about the missing environment variables on startup and then exiting.  Please have a look at the example deployment manifest in the `README`.

**Comment by lephat08** [comment]
> From your screenshot, there do not appear to be any environment variables configured for the `jibri-pod-controller` container. `jibri-pod-controller` will be logging an error about the missing environment variables on startup and then exiting. Please have a look at the example deployment manifest in the `README`.

Maybe I miss understand the documents I will add the environment to the jibri controller
Thanks for your help,
